# config.yaml

# Dataset and file paths
dataset: 'STR_dataset'
data_path: "E:\\SingleCell_AllenAtlas\\STR_Region_Expression.csv"
image_save_folder: "E:\\SingleCell_AllenAtlas\\venndiagram_drafts_VS\\Images"

# Genes of interest
genes:
  gene1: 'Crhr2'
  gene2: 'Slc32a1'
  gene3: 'Pgr'

Region_specificity:
  region: MeP
  clarifiers: 
# Venn diagram parameters
venn_settings:
  colors: ['#ff0000', '#00ff00', '#0000ff'] # Red, Green, Blue
  save_formats: ['png', 'svg']
